# Generated by Django 2.0 on 2020-08-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pphoto',
            old_name='pmodel',
            new_name='product',
        ),
    ]
